# Generated by Django 4.2.6 on 2024-05-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_started', models.DateField()),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='media/project_thumbnail')),
                ('github_link', models.URLField()),
            ],
        ),
    ]
